# Generated by Django 5.0 on 2025-10-23 19:19

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flights', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='flight',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
