# Generated by Django 5.0 on 2025-10-23 18:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('destinations', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nombre')),
                ('description', models.TextField(blank=True, verbose_name='Descripción')),
                ('icon', models.CharField(blank=True, max_length=50, verbose_name='Icono')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Categoría',
                'verbose_name_plural': 'Categorías',
                'db_table': 'categorias_paquetes',
            },
        ),
        migrations.CreateModel(
            name='Package',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Nombre del paquete')),
                ('slug', models.SlugField(blank=True, max_length=200, unique=True, verbose_name='Slug')),
                ('description', models.TextField(verbose_name='Descripción')),
                ('short_description', models.CharField(max_length=300, verbose_name='Descripción corta')),
                ('duration_days', models.PositiveIntegerField(verbose_name='Días de duración')),
                ('duration_nights', models.PositiveIntegerField(verbose_name='Noches de duración')),
                ('price_adult', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Precio adulto')),
                ('price_child', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Precio niño')),
                ('max_people', models.PositiveIntegerField(verbose_name='Máximo de personas')),
                ('min_people', models.PositiveIntegerField(default=1, verbose_name='Mínimo de personas')),
                ('includes', models.JSONField(default=list, verbose_name='Incluye')),
                ('image', models.ImageField(blank=True, null=True, upload_to='packages/', verbose_name='Imagen')),
                ('is_featured', models.BooleanField(default=False, verbose_name='Destacado')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
                ('available_from', models.DateField(verbose_name='Disponible desde')),
                ('available_until', models.DateField(verbose_name='Disponible hasta')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='packages', to='packages.category', verbose_name='Categoría')),
                ('destination', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='packages', to='destinations.destination', verbose_name='Destino')),
            ],
            options={
                'verbose_name': 'Paquete Turístico',
                'verbose_name_plural': 'Paquetes Turísticos',
                'db_table': 'paquetes_turisticos',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Itinerary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_number', models.PositiveIntegerField(verbose_name='Número de día')),
                ('title', models.CharField(max_length=200, verbose_name='Título del día')),
                ('description', models.TextField(verbose_name='Descripción')),
                ('activities', models.JSONField(default=list, verbose_name='Actividades')),
                ('meals_included', models.JSONField(default=list, verbose_name='Comidas incluidas')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('package', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itineraries', to='packages.package', verbose_name='Paquete')),
            ],
            options={
                'verbose_name': 'Itinerario',
                'verbose_name_plural': 'Itinerarios',
                'db_table': 'itinerarios_paquete',
                'ordering': ['day_number'],
                'unique_together': {('package', 'day_number')},
            },
        ),
        migrations.CreateModel(
            name='Wishlist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('added_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de agregado')),
                ('package', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wishlisted_by', to='packages.package', verbose_name='Paquete')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wishlist_items', to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'Lista de Deseos',
                'verbose_name_plural': 'Lista de Deseos',
                'db_table': 'wishlist_packages',
                'ordering': ['-added_at'],
                'indexes': [models.Index(fields=['user', '-added_at'], name='wishlist_pa_user_id_ef51ba_idx'), models.Index(fields=['package'], name='wishlist_pa_package_fa40e3_idx')],
                'unique_together': {('user', 'package')},
            },
        ),
    ]
