# Generated by Django 5.0 on 2025-10-23 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('packages', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='package',
            name='includes',
        ),
        migrations.AddField(
            model_name='package',
            name='includes_flight',
            field=models.BooleanField(default=False, verbose_name='Incluye Vuelo'),
        ),
        migrations.AddField(
            model_name='package',
            name='includes_guide',
            field=models.BooleanField(default=False, verbose_name='Incluye Guía'),
        ),
        migrations.AddField(
            model_name='package',
            name='includes_hotel',
            field=models.BooleanField(default=False, verbose_name='Incluye Hotel'),
        ),
        migrations.AddField(
            model_name='package',
            name='includes_meals',
            field=models.BooleanField(default=False, verbose_name='Incluye Comidas'),
        ),
        migrations.AddField(
            model_name='package',
            name='includes_transport',
            field=models.BooleanField(default=False, verbose_name='Incluye Transporte'),
        ),
    ]
