# Generated by Django 5.0 on 2025-10-23 08:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('destinations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('activity_type', models.CharField(choices=[('sightseeing', 'Sightseeing'), ('adventure', 'Adventure'), ('cultural', 'Cultural'), ('shopping', 'Shopping'), ('dining', 'Dining'), ('sports', 'Sports'), ('wellness', 'Wellness'), ('entertainment', 'Entertainment')], max_length=20)),
                ('description', models.TextField()),
                ('duration_hours', models.DecimalField(decimal_places=1, max_digits=4)),
                ('difficulty_level', models.CharField(choices=[('easy', 'Easy'), ('moderate', 'Moderate'), ('difficult', 'Difficult')], max_length=10)),
                ('price_per_person', models.DecimalField(decimal_places=2, max_digits=10)),
                ('max_group_size', models.PositiveIntegerField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='activities/')),
                ('is_active', models.BooleanField(default=True)),
                ('destination', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activities', to='destinations.destination')),
            ],
            options={
                'db_table': 'actividades',
                'ordering': ['name'],
            },
        ),
    ]
