# Generated by Django 5.0 on 2025-10-23 19:23

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0001_initial'),
        ('destinations', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='activity',
            options={'ordering': ['name'], 'verbose_name': 'Actividad', 'verbose_name_plural': 'Actividades'},
        ),
        migrations.AddField(
            model_name='activity',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Fecha de creación'),
        ),
        migrations.AddField(
            model_name='activity',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Última actualización'),
        ),
        migrations.AlterField(
            model_name='activity',
            name='activity_type',
            field=models.CharField(choices=[('sightseeing', 'Turismo'), ('adventure', 'Aventura'), ('cultural', 'Cultural'), ('shopping', 'Compras'), ('dining', 'Comida'), ('sports', 'Deportes'), ('wellness', 'Bienestar'), ('entertainment', 'Entretenimiento')], max_length=20, verbose_name='Tipo de actividad'),
        ),
        migrations.AlterField(
            model_name='activity',
            name='description',
            field=models.TextField(verbose_name='Descripción'),
        ),
        migrations.AlterField(
            model_name='activity',
            name='destination',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activities', to='destinations.destination', verbose_name='Destino'),
        ),
        migrations.AlterField(
            model_name='activity',
            name='difficulty_level',
            field=models.CharField(choices=[('easy', 'Fácil'), ('moderate', 'Moderado'), ('difficult', 'Difícil')], max_length=10, verbose_name='Nivel de dificultad'),
        ),
        migrations.AlterField(
            model_name='activity',
            name='duration_hours',
            field=models.DecimalField(decimal_places=1, max_digits=4, verbose_name='Duración (horas)'),
        ),
        migrations.AlterField(
            model_name='activity',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='activities/', verbose_name='Imagen'),
        ),
        migrations.AlterField(
            model_name='activity',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Activo'),
        ),
        migrations.AlterField(
            model_name='activity',
            name='max_group_size',
            field=models.PositiveIntegerField(verbose_name='Tamaño máximo del grupo'),
        ),
        migrations.AlterField(
            model_name='activity',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Nombre'),
        ),
        migrations.AlterField(
            model_name='activity',
            name='price_per_person',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Precio por persona'),
        ),
    ]
