# Generated by Django 5.0 on 2025-10-23 18:32

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('bookings', '0001_initial'),
        ('packages', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('overall_rating', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='Calificación General')),
                ('accommodation_rating', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='Calificación Alojamiento')),
                ('transport_rating', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='Calificación Transporte')),
                ('guide_rating', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='Calificación Guía')),
                ('value_rating', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='Calificación Relación Calidad-Precio')),
                ('title', models.CharField(max_length=200, verbose_name='Título')),
                ('comment', models.TextField(verbose_name='Comentario')),
                ('pros', models.TextField(blank=True, null=True, verbose_name='Aspectos Positivos')),
                ('cons', models.TextField(blank=True, null=True, verbose_name='Aspectos Negativos')),
                ('is_verified', models.BooleanField(default=False, verbose_name='Verificada')),
                ('is_approved', models.BooleanField(default=False, verbose_name='Aprobada')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('booking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='bookings.booking', verbose_name='Reserva')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to=settings.AUTH_USER_MODEL, verbose_name='Cliente')),
                ('package', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='packages.package', verbose_name='Paquete')),
            ],
            options={
                'verbose_name': 'Reseña',
                'verbose_name_plural': 'Reseñas',
                'db_table': 'resenas',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['package', '-created_at'], name='resenas_package_561784_idx'), models.Index(fields=['customer'], name='resenas_custome_1352cf_idx'), models.Index(fields=['is_approved', '-created_at'], name='resenas_is_appr_edf742_idx')],
            },
        ),
    ]
