# Generated by Django 5.0 on 2025-10-23 18:32

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('packages', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Coupon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50, unique=True, verbose_name='Código del cupón')),
                ('description', models.CharField(max_length=200, verbose_name='Descripción')),
                ('discount_type', models.CharField(choices=[('percentage', 'Porcentaje'), ('fixed', 'Monto fijo')], max_length=20, verbose_name='Tipo de descuento')),
                ('discount_value', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Valor del descuento')),
                ('min_purchase_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Compra mínima')),
                ('max_discount_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Descuento máximo')),
                ('valid_from', models.DateField(verbose_name='Válido desde')),
                ('valid_until', models.DateField(verbose_name='Válido hasta')),
                ('max_uses', models.IntegerField(blank=True, null=True, verbose_name='Usos máximos')),
                ('times_used', models.IntegerField(default=0, verbose_name='Veces usado')),
                ('is_active', models.BooleanField(default=True, verbose_name='¿Está activo?')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
            ],
            options={
                'verbose_name': 'Cupón',
                'verbose_name_plural': 'Cupones',
                'db_table': 'cupones',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Wishlist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('added_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de agregado')),
                ('package', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wishlists', to='packages.package', verbose_name='Paquete')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wishlist', to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'Lista de Deseos',
                'verbose_name_plural': 'Listas de Deseos',
                'db_table': 'lista_deseos',
                'ordering': ['-added_at'],
                'unique_together': {('user', 'package')},
            },
        ),
    ]
