# Generated by Django 5.0 on 2025-10-23 18:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('bookings', '0001_initial'),
        ('flights', '0001_initial'),
        ('hotels', '0001_initial'),
        ('packages', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='package_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bookings', to='packages.package'),
        ),
        migrations.AddField(
            model_name='flightbooking',
            name='booking_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='flight_bookings', to='bookings.booking'),
        ),
        migrations.AddField(
            model_name='flightbooking',
            name='flight_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='flight_reservations', to='flights.flight'),
        ),
        migrations.AddField(
            model_name='hotelbooking',
            name='booking_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hotel_bookings', to='bookings.booking'),
        ),
        migrations.AddField(
            model_name='hotelbooking',
            name='hotel_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hotel_reservations', to='hotels.hotel'),
        ),
        migrations.AddField(
            model_name='passenger',
            name='booking_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='passengers', to='bookings.booking'),
        ),
    ]
